version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Maven...
      - mvn clean install -DskipTests
  build:
    commands:
      - echo Building...
      - mvn package -DskipTests
artifacts:
  files:
    - target/*.war

